In [14]:
import torch

In [15]:
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

x = torch.tensor([5.5, 3])
print(x)

x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[7.0715e-39, 1.0653e-38, 9.7347e-39],
        [4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39]])
tensor([[0.1314, 0.1268, 0.2195],
        [0.4000, 0.8176, 0.2562],
        [0.6249, 0.3520, 0.9745],
        [0.6885, 0.4392, 0.3463],
        [0.7075, 0.7792, 0.6957]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4499, -1.9741, -0.5165],
        [ 0.5432, -0.4789, -2.1676],
        [-1.4314,  0.1402,  0.6525],
        [-1.0603,  1.0726, -0.5580],
        [-0.8997,  0.6110,  0.0468]])
torch.Size([5, 3])


In [16]:
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x)  # Any operation that mutates a tensor in-place is post-fixed with an _.
print(y)

y += 1
print(y)

print(x[:, 1])

tensor([[ 1.5519, -1.6431,  0.0872],
        [ 1.3958, -0.1906, -1.2091],
        [-0.7778,  1.1099,  1.3758],
        [-0.1029,  1.6134,  0.1344],
        [-0.3277,  0.7191,  0.6320]])
tensor([[ 1.5519, -1.6431,  0.0872],
        [ 1.3958, -0.1906, -1.2091],
        [-0.7778,  1.1099,  1.3758],
        [-0.1029,  1.6134,  0.1344],
        [-0.3277,  0.7191,  0.6320]])
tensor([[ 1.5519, -1.6431,  0.0872],
        [ 1.3958, -0.1906, -1.2091],
        [-0.7778,  1.1099,  1.3758],
        [-0.1029,  1.6134,  0.1344],
        [-0.3277,  0.7191,  0.6320]])
tensor([[ 1.5519, -1.6431,  0.0872],
        [ 1.3958, -0.1906, -1.2091],
        [-0.7778,  1.1099,  1.3758],
        [-0.1029,  1.6134,  0.1344],
        [-0.3277,  0.7191,  0.6320]])
tensor([[ 2.5519, -0.6431,  1.0872],
        [ 2.3958,  0.8094, -0.2091],
        [ 0.2222,  2.1099,  2.3758],
        [ 0.8971,  2.6134,  1.1344],
        [ 0.6723,  1.7191,  1.6320]])
tensor([-1.9741, -0.4789,  0.1402,  1.0726,  0.6110])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2526])
-0.2525639832019806


In [19]:
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.7474], device='cuda:0')
tensor([0.7474], dtype=torch.float64)


In [21]:
#######################################
# Autograd: Automatic Differentiation #
#######################################

In [22]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()
print(z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [23]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


In [24]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [25]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

v = torch.tensor([.1, 1., .0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([-1218.7263,  -190.3329, -1497.5757], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [26]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
True
False
True
False
tensor(True)
